function rate_params = nel_plot_pst_params(line_dur, stim_dur)
%

% adapted by GE (28Jul2003) from "default_plot_rate_params" written by AF 10/9/01.

if (exist('line_dur','var') ~= 1)
   line_dur = 1;
end
if (exist('stim_dur','var') ~= 1)
   stim_dur = 0.5;
end

rate_params.func = 'nel_plot_pst';    % modified by GE 28Jul2003.
rate_params.line_dur = line_dur;
rate_params.stim_dur = stim_dur;

rate_params.pst = struct( ...
   'firstBin_sec',         0 ...
   ,'lastBin_sec',  line_dur ...
... %... % MH 11Dec2003: hard coded
... %   ,'lastBin_sec',  stim_dur+.015 ...
   ,'binWidth_sec',  max(stim_dur/200, 0.0005) ...
   ,'nullThreshold',     500 ...
   );

rate_params.props.axes = struct( ...
   'Tag',         'rate' ...
   ,'Box',        'on' ...
   ,'Color',      'k' ...
   ,'Xdir',       'reverse' ...
   ,'XLim',       [0 50] ...
   ,'XTick',      [0 50 100:100:1000] ...
   );

rate_params.props.driven = struct( ...
   'Tag',         'driven' ...
   ,'LineStyle',  '-' ...
   ,'LineWidth',  1 ...
   ,'Marker',     'none' ...
   ,'Color',      'r' ...
   ,'EraseMode',  'back' ...
   );

rate_params.props.xlabel = struct( ...
   'fontsize',   14 ...
   );
rate_params.props.ylabel = struct( ...
   'fontsize',   14 ...
   );


