function my_startup
% MY_STARTUP personlized startup file for nel users
%
% MH 12/14/01
% 29Jun2004 added choice of experiment type (M.Heinz)
% 8/17/2016 copied from MH

global VM_root_dir VM_exp_type 

VM_root_dir = [fileparts(which('my_startup')) filesep];

addpath([VM_root_dir  'myMfiles']);
addpath([VM_root_dir  'Templates']);
exp_options = {'AN_TTS','General'};
s = listdlg('PromptString','Select Experiment Type:',...
    'SelectionMode','single',...
    'ListString', exp_options);
VM_exp_type = exp_options{s};

switch (VM_exp_type)
case 'AN_TTS'
    VM_Templates = struct(...
        'SR',                    'SR_template', ...        
        'PST',                   'PSTlong_template2', ...
        'BF_RLV',                'BF_RLVlong_template', ...
        'BBNrlv_quick',          'BBNrlv_quick_template2', ...
        'BBNlong2',              'BBNlong2_template' ...
        );
case 'General'
    VM_Templates = struct(...
        'SR',                    'SR_template', ...
        'SNRenvrlv_QUICK',       'SNRenvrlv_quick_template', ...
        'SNRenv',                'SNRenv_template' ...
        );
end

register_user_templates(VM_Templates);
