function my_startup
% MY_STARTUP personlized startup file for nel users
%
% MH 12/14/01
% 29Jun2004 added choice of experiment type (M.Heinz)

global MH_root_dir MH_exp_type 

MH_root_dir = [fileparts(which('my_startup')) filesep];

addpath([MH_root_dir  'myMfiles']);
addpath([MH_root_dir  'Vowel Synthesis']);
addpath([MH_root_dir  'Templates']);
exp_options = {'NOHR', 'CN','AN_RLFs'};
s = listdlg('PromptString','Select Experiment Type:',...
   'SelectionMode','single',...
   'ListString', exp_options);
MH_exp_type = exp_options{s};

switch (MH_exp_type)
case 'NOHR'
   MH_Templates = struct(...
      'TrBF',                'Tone_reBF_template', ...
      'EHrlv',               'EHrlv_template', ...
      'EHrBFi',              'EH_reBFi_template', ...
      'EHrBF',               'EH_reBF_template', ...
...%      'Trlv',                'BF_RLV_template', ...
      'EHrFF',               'EH_reFF_template', ...
      'TrFF',                'Tone_reFF_template' ...
... %      'RM',                  'RM_template' ...
      );
case 'AN_RLFs'
   MH_Templates = struct(...
      'T2',                  'T2_template', ...
      'T1',                  'T1_template', ...
      'TB',                  'TB_template', ...
      'FN',                  'FN_template', ...
      'SP',                  'SP_template', ...
      'T05',                 'T05_template', ...
      'B2',                  'B2_template', ...
      'B1',                  'B1_template', ...
      'BD',                  'BD_template', ...
      'FW',                  'FW_template', ...
      'FWC',                 'FWCEFS_template', ...
      'TX',                  'TX_template' ...
      );
case 'CN'
   MH_Templates = struct(...
      'RM2T',                'RM2T_template', ...
      'EH',                  'EH_template' ...
      );
end

register_user_templates(MH_Templates);
