% Written by GE_MH 04nov2003. Modified EDY 5/10/05.
% Modified M Heinz 8/3/07
% SP on 17 Feb, 2020: Modified SNRenv_0.m

global signals_dir

% Random order using Matlab randsample 
files ={
    'SpeechOnSpeech_SNR_0_N.wav', ...
    'SpeechOnSpeech_SNR_plusInf_N.wav', ...
    'SpeechOnSpeech_SNR_minus6_N.wav', ...
    'SpeechOnSpeech_SNR_minus6_P.wav', ...
    'SpeechOnSpeech_SNR_0_P.wav', ...
    'SpeechOnSpeech_SNR_plus6_N.wav', ...
    'SpeechOnSpeech_SNR_plusInf_P.wav', ...
    'SpeechOnSpeech_SNR_minusInf_P.wav', ...
    'SpeechOnSpeech_SNR_minusInf_N.wav',...
    'SpeechOnSpeech_SNR_plus6_P.wav'};

Lchannel.file_list = cell(length(files),1);

for i=1:length(files)
    Lchannel.file_list{i} = sprintf('%sMH\\Speech_On_Speech_MF\\%s', signals_dir,files{i});
end
