%Search Instruction Block

Stimuli = struct('freq_hz',5000, ...
    'atten',    50, ...
    'duration', 50, ...
    'period',  250, ...
    'channel',   3, ...
    'KHosc',     0, ...
    'fmult',    10, ...
    'calibPicNum',    nan, ...
    'spike_channel', 1);   % added by GE 17Jan2003.

