function my_startup
% MY_STARTUP personlized startup file for nel users

global AF_root_dir

AF_root_dir = [fileparts(which('my_startup')) filesep];

addpath([AF_root_dir  'Templates']);

AF_Templates = struct(...
            'SR',                    'SR_template', ...
            'PST30',                   'PSTlong_template2', ...
            'PSTn10',                   'PSTlong_template2_n10dB', ...
            'PSTn5',                   'PSTlong_template2_n5dB', ...
            'PST0',                   'PSTlong_template2_0dB', ...
            'PST5',                   'PSTlong_template2_5dB', ...
            'PST10',                   'PSTlong_template2_10dB', ...
            'BF_RLV',                'BF_RLVlong_template', ...
            'SAMtone',              'SAMtone_template' ,...
            'SAM_swept',            'SAM_TMDF_swept_template',...
            'SAM_TMDF_withnoise',    'SAM_TMDF_template_MS',...
            'SAM_TMDF_LF',              'SAM_TMDF_template_LF',...
            'WAVreBFi',              'WAVreBFi_template', ...
            'BOYrlv_QUICK',           'BOYrlv_quick_template',...
            'SAM_TMDF',              'SAM_TMDF_template'...
            );

register_user_templates(AF_Templates);
