%Search Instruction Block

Stimuli = struct('freq_hz',500, ...
    'atten',    30, ...
    'duration', 50, ...
    'period',  250, ...
    'channel',   3, ...
    'KHosc',     0, ...
    'fmult',    1, ...
    'spike_channel', 1);   % added by GE 17Jan2003.

