% To send you to the specific AEP measure

global RunThroughABRFlag
RunThroughABRFlag=0;

interface_type=questdlg('Select AEP Measure:','AEP','CAP','ABR','FFR','CAP'); %SP 30Jun2016

if strcmp(interface_type,'FFR')
    command_str='close';
end

if strcmp(interface_type,'ABR')
    ABR_ins; 
    %interface_type='ABR';
end

if strcmp(interface_type,'CAP')
    CAP_ins;
    %interface_type=questdlg('Select CAP Measure:','CAP','CAP (RW)','ECochG (EarCanal)','CAP (fMask)','CAP (RW)'); %SP 30Jun2016
end

Stimuli.RPsamprate_Hz=12207.03125;  % Hard coded for now, eventually get from RP

% 
% switch interface_type
% 
%      case 'ABR'
%      RunThroughABRFlag=1;
%      
%     % CAP at Round Window
% 	case 'CAP (RW)'
%    
% 		misc = struct( ... 
%            'fileExtension', 'CAP1f' ...
%           ); 
%       
% 		Stimuli = struct( ...
%            'freq_hz',2000, ...
%            'atten_dB', 40, ...
%            'fast', struct( ...
%                   'duration_ms', 10, ...
%                   'rftime_ms',  1, ...
%                   'period_ms',  50, ...
%                   'XstartPlot_ms',0, ...
%                   'XendPlot_ms',25, ...
%                   'CAPlength_ms',25), ...
%            'slow', struct( ...
%                   'duration_ms', 10, ...
%                   'rftime_ms',  1, ...
%                   'period_ms',  250, ...
%                   'XstartPlot_ms',0, ...
%                   'XendPlot_ms',25, ...
%                   'CAPlength_ms',25), ...
%            'fixedPhase', 0,  ...
%            'channel',   3, ...
%            'KHosc',     0, ...
%            'fmult',    10, ...
%            'CAPmem_reps',  30, ...
%            'threshV', 2, ... %for artifact rejection KH 2012 Jan 05
%            'clickYes', 1, ... % added by KH 06Jan2012
%            'clickLength_ms', 0.04, ... %KH 10Jan2012
%            ... %not cleaned up yet
%            'ear', 'both' ...  % set in CAP.m
%            );
% 	
% % %% ORIG       'nPairs', 20, ...
% %            'stepdB', 5, ...
% %            'attenMask', [12:-1:0], ...
% 
% 		RunLevels_params = struct( ... 
%            'nPairs', 20, ...
%            'stepdB', 5, ...
%            'attenMask', [12:-1:0], ...
%            'audiogramFreqs', [500 1000 2000 4000 8000], ... %KH 10Jan2012
%            'decimateFact', 1, ...
%            'saveRepsYes', 1, ... %added by KH 6
%            'bMultiOutputFiles', 0 ...  % added by GE 26Apr2004.
%           ); 
%    
%       Display = struct( ... 
%          'Gain', 1000, ...  
%          'YLim_atAD', 0.8, ...
%          'Voltage', 'atELEC' ...
%          ); 
%      
%      
%     %% Ear Canal ECochG (more reps)    
% 	case 'ECochG (EarCanal)'
%    
% 		misc = struct( ... 
%            'fileExtension', 'CAP1f' ...
%           ); 
%       
% 		Stimuli = struct( ...
%            'freq_hz',2000, ...
%            'atten_dB', 20, ...
%            'fast', struct( ...
%                   'duration_ms', 10, ...
%                   'rftime_ms',  1, ...
%                   'period_ms',  43, ...
%                   'XstartPlot_ms',0, ...
%                   'XendPlot_ms',25, ...
%                   'CAPlength_ms',25), ...
%            'slow', struct( ...
%                   'duration_ms', 10, ...
%                   'rftime_ms',  1, ...
%                   'period_ms',  250, ...
%                   'XstartPlot_ms',0, ...
%                   'XendPlot_ms',25, ...
%                   'CAPlength_ms',25), ...
%            'fixedPhase', 0,  ...
%            'channel',   3, ...
%            'KHosc',     0, ...
%            'fmult',    10, ...
%            'CAPmem_reps',  50, ...
%            'threshV', 2, ... %for artifact rejection KH 2012 Jan 05
%            'clickYes', 1, ... % added by KH 06Jan2012
%            'clickLength_ms', 0.04, ... %KH 10Jan2012
%            ... %not cleaned up yet
%            'ear', 'both' ...  % set in CAP.m
%            );
% 		RunLevels_params = struct( ... 
%            'nPairs', 1000, ...
%            'stepdB', 5, ...
%            'attenMask', 0, ...     %[3:-1:-9], ...
%            'audiogramFreqs', [500 1000 2000 4000 8000], ... %KH 10Jan2012
%            'decimateFact', 1, ...
%            'saveRepsYes', 1, ... %added by KH 6
%            'bMultiOutputFiles', 0 ...  % added by GE 26Apr2004.
%           ); 
%    
%       Display = struct( ... 
%          'Gain', 50000, ...  
%          'YLim_atAD', 0.8, ...
%          'Voltage', 'atELEC' ...
%          ); 
% 
%      
%      
%   
% 
% end


% MH/GE 11/03/03: eventually add a param for AD channel