%CAP Instruction Block

Stimuli = struct( ...
   'freq_hz',5000, ...
   'atten_dB',    50, ...
   'duration_ms', 10, ...
   'period_ms',  250, ...
   'fixedPhase', 0,  ...
   'channel',   3, ...
   'KHosc',     0, ...
   'fmult',    10, ...
   'CAPlength_sec',   .05, ...
   'CAPmem_reps',  0, ...
   ... %not cleaned up yet
   'ear', 'both', ...  % set in CAP.m
   'RPsamprate_Hz', 97656.25 ...  % Hard coded for now, eventually get from RP
   );

RunLevels_params = struct( ...
   'nPairs', 2, ...
   'stepdB', 5, ...
   'attenMask', [1 0 -1], ...
   'decimateFact', 10 ...
  ); 


% MH/GE 11/03/03: eventually add a param for AD channel
