%CAP Instruction Block

interface_type = 'fmasked_CAPs';

misc = struct( ... 
   'fileExtension', 'fmasked_CAP' ...
  ); 

Stimuli = struct( ...
   'atten_dB', 40, ...  %click atten
   'masker_atten_dB', 60, ... %masker atten
   'fast', struct( ...
          'duration_ms', 50, ...   %Masker On (total duration)
          'rftime_ms',  20, ...  %Gating time WARNING!: this value is hard coded in RPvdsEx (CosGate), must be duplicated
          'period_ms',  75, ... %67  %Time between two onsets of stimuli (maskers) - = 'StmOff' + duration_ms 
          'XstartPlot_ms',0, ...
          'XendPlot_ms',12, ...
          'CAPlength_ms',12, ...
          'clickDelay', 14), ... %14
   'slow', struct( ...
          'duration_ms', 80, ...
          'rftime_ms',  7, ...
          'period_ms',  110, ...
          'XstartPlot_ms',0, ...
          'XendPlot_ms',14, ...
          'CAPlength_ms',14, ...
          'clickDelay', 50), ...
   'fixedPhase', 0,  ...
   'channel',   3, ...
   'KHosc',     0, ...
   'CAPmem_reps',  30, ...
   'threshV', 2, ... %for artifact rejection KH 2012 Jan 05
   'ear', 'both' ...  % set in CAP.m
   );

 RunLevels_params = struct( ... 
    'nPairs', 10, ...
    'stepdB', 5, ...
    'attenMask', [12:-1:0], ...
    'decimateFact', 2, ...
    'saveRepsYes', 1  ); 
    %NB - structure also used for RunStimuli
     %'bMultiOutputFiles', 0 ...  %not useful, 1 file per stimuli by
     %default

Display = struct( ... 
 'Gain', 1000, ...  
 'YLim_atAD', 0.8, ...
 'Voltage', 'atELEC' ...
 ); 

     
Stimuli.RPsamprate_Hz= 48828; %12207.03125;  % Hard coded for now, eventually get from RP
              
% MH/GE 11/03/03: eventually add a param for AD channel
