% EFR_Harmonic Complex Instruction Block
function [misc,Stimuli, RunLevels_params, Display, interface_type]=EFR_Harm_Cmplx_ins(NelData)

% SNRenvStimDir='C:\NEL1_2\Users\SP\SNRenv_stimuli\stimSetStationary\'; %
% This was the data dir for pilot data before DTU. (Q313 and Q314).

CodesDir= 'C:\NEL1_2\Users\SP\create_harmonic_complex_ffr_hf_vs_lf/';
DataDir= NelData.File_Manager.dirname;
RootDir= pwd;


cd (CodesDir);
plotFlag= 0;
% initialize this variable to create stim and update the struct stim
temp.dur_ms= 2000;
aud_fName_full= create_cf_lf_ratio_stims_cont(temp.dur_ms, DataDir, plotFlag);
[SNRenvStimDir, aud_fName, aud_ext]= fileparts(aud_fName_full);
if ~strcmp(SNRenvStimDir(end), filesep)
    SNRenvStimDir= [SNRenvStimDir filesep];
end
cd (RootDir);

aud_fName= [aud_fName aud_ext];

interface_type = 'EFR_HrmCpx'; % ge debug ABR
% interface_type = 'SPIKES';
%            'filename','C:\NEL_debug\Nel_matlab\FFR\object\tone.wav',...
switch interface_type
    case 'EFR_HrmCpx'
        misc = struct( ...
            'fileExtension', 'EFR_', ...
            'n',0 ...%zz oct2011
            );
        
        %         fName=load([fileparts(SNRenvStimDir(1:end-1)) filesep 'SNRenv_stimlist14.mat']); % for Pilot SFR
        fName= struct('name', aud_fName);
        
        Stimuli = struct( ...
            'pol',1,...%zz 31oct2011
            'list',fName, ...
            'filename',fName(1).name,...
            ...%'freq_hz',2000, ...
            'atten_dB', 40, ...
            'NoiseType',0,... % 0 for stationary, 1 for fluctuating
            'maxSPL', 90, ...
            'STIMfile', 'C:\NEL1_2\Nel_matlab\FFR\Signals\tone_org.wav', ...
            'UPDdir', 'C:\NEL1_2\Nel_matlab\FFR\FFRSNRenv_short_stationary_run\', ... (copy resampled files here) % ideally this should be in data dir (SP --> to-do)
            'OLDDir', SNRenvStimDir, ... (from here)
            ...
            ...
            'fast', struct( ...
            ... %zz 17jan12
            'duration_ms', temp.dur_ms, ... % 1728 for pilot, 1300 for short
            'rftime_ms',  10, ...
            'period_ms',  temp.dur_ms+500, ... % repitition rate
            'XstartPlot_ms',0, ...
            'XendPlot_ms',temp.dur_ms+400, ... % plot close to end
            'FFRlength_ms',temp.dur_ms+200), ... % don't save everything,
            ... % give NEL buffer time so that nothing gets skipped
            ...
            ...
            'slow', struct( ...
            ...% ZZ 18nov11
            'duration_ms', 1300, ... % AEH 1/27/14 500 ms
            'rftime_ms',  10, ...
            'period_ms',  2728, ... % AEH 1/27/14 750 ms
            'XstartPlot_ms',0, ...
            'XendPlot_ms', 2728, ...
            'FFRlength_ms',1750), ...
            ...%'fixedPhase', 1,  ...
            ...
            'channel',   3, ...
            'KHosc',     0, ...
            'fmult',    10, ...
            'FFRmem_reps',  100, ...
            'threshV', 100, ... (.4) %for artifact rejection KH 2011 Jun 08
            ... %not cleaned up yet
            'ear', 'both' ...  % set in FFR.m
            );
        
        RunLevels_params = struct( ...
            'nPairs', 300, ...
            'nPairs_actual', 300, ...
            'doneStims', zeros(length(fName),1), ...
            'stepdB', 0, ...
            'attenMask', 0, ...
            'decimateFact', 1, ...
            'bMultiOutputFiles', 0 ...  % added by GE 26Apr2004.
            );
        
        Display = struct( ...
            'Gain', 2e4,... 20000, ...
            'YLim_atAD', 0.1, ...
            'Voltage', 'atELEC' ...
            );
        
    case 'SPIKES'
        
        misc = struct( ...
            'fileExtension', 'SPIKES', ...
            'n',0 ...%zz oct2011
            );
        
        Stimuli = struct( ...
            'fc',1000,...%zz 31oct2011
            'fm',140,...%zz 31oct2011
            ...%'dur',1,...%zz 31oct2011
            'pol',1,...%zz 31oct2011
            'mod',1,...
            'filename','C:\NEL1_2\Nel_matlab\FFR\object\tone_org.wav',...%zz 31oct2011
            ...%'freq_hz',2000, ...
            'atten_dB', 40, ...
            'noNoise', 1, ...
            'noiseLevel', 10, ...
            'fast', struct( ...
            ... %zz 17jan12
            'duration_ms', 500, ...
            'rftime_ms',  10, ...
            'period_ms',  1000, ...
            'XstartPlot_ms',0, ...
            'XendPlot_ms',1000, ...
            'FFRlength_ms',600), ...
            'slow', struct( ...
            ...% ZZ 18nov11
            'duration_ms', 250, ...     % stim duration
            'rftime_ms',  10, ...
            'period_ms',  1000, ...     % repetition period
            'XstartPlot_ms',0, ...
            'XendPlot_ms',500, ...      % plotting duration
            'FFRlength_ms',300), ...    % recording time
            ...%'fixedPhase', 1,  ...
            'channel',   3, ...
            'KHosc',     0, ...
            'fmult',    10, ...
            'FFRmem_reps',  100, ...
            'threshV', 0.4, ... %for artifact rejection KH 2011 Jun 08
            ... %not cleaned up yet
            'ear', 'both' ...  % set in FFR.m
            );
        
        RunLevels_params = struct( ...
            'nPairs', 500, ...
            'nPairs_actual', 500, ...
            'stepdB', 5, ...
            'attenMask', 0, ...
            'decimateFact', 1, ...
            'bMultiOutputFiles', 0 ...  % added by GE 26Apr2004.
            );
        
        Display = struct( ...
            'Gain', 20000, ...
            'YLim_atAD', 0.1, ...
            'Voltage', 'atELEC', ...
            'PlotFactor', 1 ...
            );
end
% Stimuli.RPsamprate_Hz=12207.03125*4;
% Stimuli.RPsamprate_Hz=12207.03125;  % Hard coded for now, eventually get from RP


Stimuli.RPsamprate_Hz=25e6/512; %48828.125  % Hard coded for now, eventually get from RP