function my_startup
% MY_STARTUP personlized startup file for nel users
%
% MH 12/14/01
% 29Jun2004 added choice of experiment type (M.Heinz)

global MH_root_dir MH_exp_type SKIPintro

MH_root_dir = [fileparts(which('my_startup')) filesep];

addpath([MH_root_dir  'myMfiles']);
addpath([MH_root_dir  'Vowel Synthesis']);
addpath([MH_root_dir  'Templates']);

if SKIPintro
    disp('HARD CODED USER TEMPLATE list')
    MH_exp_type = 'AN_TTS_1';
else
    % exp_options = {'R03-AN', 'R03-CN', 'CN','AN_RLFs'};
    exp_options = {'AN_TTS_1','ISH2009','CHIM_BBN','R03-AN_CN', 'CN','AN_RLFs'};
    s = listdlg('PromptString','Select Experiment Type:',...
        'SelectionMode','single',...
        'ListString', exp_options);
    MH_exp_type = exp_options{s};
end

switch (MH_exp_type)
    case 'AN_TTS_1'
        %     MH_Templates = struct(...
        %         'SR',                    'SR_template', ...
        %         'PST',                   'PSTlong_template', ...%02022016-MKW exchanged for PSTlong_template2(below)
        %02022016-MKW 'PSTlong_template' exchanged for 300/700/2.5ms,on/off/rf PSTlong_template2 to match Westerman&Smith,HearRes1984
        MH_Templates = struct(...
            'SR',                    'SR_template', ...
            'PST',                   'PSTlong_template2', ...
            'BF_RLV',                'BF_RLVlong_template', ...
            'BBNrlv_quick',          'BBNrlv_quick_template2', ...
            'BBNlong',               'BBNlong_template', ...
            'BBNlong2',              'BBNlong2_template', ...
            'SNRenvrlv_QUICK',       'SNRenvrlv_quick_template', ...
            'SNRenv',                'SNRenv_template', ...
            'SNRenvSSN',             'SNRenv_SSN_template', ...
            'SNRenvFLN',             'SNRenv_FLN_template', ...
            'SNRenv_min10',          'SNRenv_min10_template', ...
            'SNRenv_min5',           'SNRenv_min5_template', ...
            'SNRenv_0',              'SNRenv_0_template', ...
            'EHINvN_reBFi',          'EHINvN_reBFi_template', ...
            'syncCAP',               'syncCAP_reBFi_template' ...
            );
    case 'ISH2009'
        MH_Templates = struct(...
            'SR',                    'SR_template', ...
            'BF_RLV',                'BF_RLV_template', ...
            'PST',                   'PST_template', ...
            'BBN_A_rlv_QUICK',       'BBN_A_rlv_quick_template', ...
            'BOYrlv_QUICK',          'BOYrlv_quick_template', ...
            'WAVreBFi',              'WAVreBFi_template' ...
            );
    case 'CHIM_BBN'
        MH_Templates = struct(...
            'PST',                   'PST_template', ...
            'CHrlv_QUICK',           'CHrlv_quick_template', ...
            'Chimera',               'Chimera_template', ...
            'BBNrlv_QUICK',          'BBNrlv_quick_template', ...
            'BBN_SCCXCC',            'BBN_SCCXCC_template' ...
            );
        % case 'R03-AN'
        %    MH_Templates = struct(...
        %       'SACrlv_QUICK',          'SACrlv_quick_template', ...
        %       'SACrlv',                'SACrlv_template', ...
        %       'EHrlv',                 'EHrlv_template', ...
        %       'EH_INrlv',              'EH_INrlv_template', ...
        %       'EHINvN_reBFi',          'EHINvN_reBFi_template', ...
        %       'TEHrBFi',               'TEH_reBFi_template', ...
        %     'SAMtone',              'SAMtone_template', ...
        %     'SAMtone_IN',               'SAMtone_IN_template', ...
        %       'TONErlv',               'TONErlv_template', ...
        %       'TONErBFi',              'TONE_reBFi_template', ...
        %       'EHrlv_IN',              'EHrlv_IN_template', ...
        %       'EHINvS_reBFi',          'EHINvS_reBFi_template', ...
        %       'ToneINvS_reBFi',        'ToneINvS_reBFi_template' ...
        %       );
        % %      'EHrBFi',              'EH_reBFi_template', ...
        % %      'TrBF',                'Tone_reBF_template', ...
        % %      'TrFF',                'Tone_reFF_template', ...
        % %      'EHrBF',               'EH_reBF_template', ...
        % %      'EHrFF',               'EH_reFF_template' ...
    case 'R03-AN_CN'
        MH_Templates = struct(...
            'BF_RLV',                'BF_RLV_template', ...
            'NO_RLV',                'NO_RLV_template', ...
            'PST',                   'PST_template', ...
            'PSTasync',              'PSTasync_template', ...
            'SACrlv_QUICK',          'SACrlv_quick_template', ...
            'SACrlv',                'SACrlv_template', ...
            'EHrlv',                 'EHrlv_template', ...
            'EH_INrlv',              'EH_INrlv_template', ...
            'EHINvN_reBFi',          'EHINvN_reBFi_template', ...
            'SAMtone',               'SAMtone_template', ...
            'SAMtone_IN',            'SAMtone_IN_template', ...
            'SAM_TMTF',              'SAM_TMTF_template',...
            'SAM_TMDF',              'SAM_TMDF_template',...
            'EH_SFS',                'SFS_template', ...
            'EH_SFS_IN',             'SFS_IN_template' ...
            );
        %       'RM',                    'RM_template', ...
        %       'RM2T',                  'RM2T_template', ...
        %       'TEHrBFi',               'TEH_reBFi_template', ...
        %       'TONErBFi',              'TONE_reBFi_template', ...
        %       'BF_RLVinNO',            'BF_RLVinNO_template', ...
        %       'EHrlv_IN',              'EHrlv_IN_template', ...
        %       'EHINvS_reBFi',          'EHINvS_reBFi_template', ...
        %       'ToneINvS_reBFi',        'ToneINvS_reBFi_template' ...
        %       'TONErlv',               'TONErlv_template', ...
        %      'EHrBFi',              'EH_reBFi_template', ...
        %      'TrBF',                'Tone_reBF_template', ...
        %      'TrFF',                'Tone_reFF_template', ...
        %      'EHrBF',               'EH_reBF_template', ...
        %      'EHrFF',               'EH_reFF_template' ...
    case 'AN_RLFs'
        MH_Templates = struct(...
            'T2',                  'T2_template', ...
            'T1',                  'T1_template', ...
            'TB',                  'TB_template', ...
            'FN',                  'FN_template', ...
            'SP',                  'SP_template', ...
            'T05',                 'T05_template', ...
            'B2',                  'B2_template', ...
            'B1',                  'B1_template', ...
            'BD',                  'BD_template', ...
            'FW',                  'FW_template', ...
            'FWC',                 'FWCEFS_template', ...
            'TX',                  'TX_template' ...
            );
    case 'CN'
        MH_Templates = struct(...
            'RM2T',                'RM2T_template', ...
            'EH',                  'EH_template' ...
            );
        %    'BF_RLV',              'BF_RLV_template', ...
        %    'NO_RLV',              'NO_RLV_template', ...
        %    'BF_RLVinNO',          'BF_RLVinNO_template', ...
        %    'PST',                 'PST_template', ...
        %    'PSTasync',            'PSTasync_template', ...
        %    'RM',                  'RM_template', ...
        %    'RM2T',                'RM2T_template', ...
end

register_user_templates(MH_Templates);