function my_startup
% MY_STARTUP personlized startup file for nel users

% SP 12/17/15

global SP_root_dir

SP_root_dir = [fileparts(which('my_startup')) filesep];

addpath([SP_root_dir  'Templates']);

SP_Templates = struct(...
    'SR',                    'SR_template', ...
    'PST',                   'PSTlong_template', ...
    'BF_RLV',                'BF_RLVlong_template', ...
    'BBNrlv_quick',          'BBNrlv_quick_template2', ...
    'BBNlong',               'BBNlong_template', ...
    'SNRenvrlv_QUICK',       'SNRenvrlv_quick_template', ...
    'SNRenv',                'SNRenv_template' ...
    );

register_user_templates(SP_Templates);
